// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3pph1Bx4T2go8FAYoMmKOWYFdtcGHv-U',
    appId: '1:745520213848:android:38347c33e10ea66e453f2d',
    messagingSenderId: '745520213848',
    projectId: 'messenger-nurs',
    storageBucket: 'messenger-nurs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9yOXeU6dyBMQEN_bBdGV0__WicFdZHuo',
    appId: '1:745520213848:ios:ccdfb97424776595453f2d',
    messagingSenderId: '745520213848',
    projectId: 'messenger-nurs',
    storageBucket: 'messenger-nurs.appspot.com',
    androidClientId: '745520213848-s4a937to253eo2gc2afm5gbpjaod2lvk.apps.googleusercontent.com',
    iosClientId: '745520213848-k096sl474p44m2hbd37ppe5et2ksgsgj.apps.googleusercontent.com',
    iosBundleId: 'com.example.messengerNurs',
  );

}